version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=1
    command: streamlit run nlp_evolution_app.py --server.port 8501 --server.address 0.0.0.0 --server.runOnSave true
    restart: unless-stopped 