name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Quality Checks"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m nltk.downloader punkt brown

    - name: Cache NLTK data
      uses: actions/cache@v3
      with:
        path: ~/nltk_data
        key: nltk-data-${{ runner.os }}

    # Add your deployment steps here
    # For example, if deploying to Streamlit Cloud:
    # - name: Deploy to Streamlit Cloud
    #   env:
    #     STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
    #   run: |
    #     # Add deployment commands 