name: Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort bandit safety
        python -m nltk.downloader punkt brown
    
    - name: Cache NLTK data
      uses: actions/cache@v3
      with:
        path: ~/nltk_data
        key: nltk-data-${{ runner.os }}
    
    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=. --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
    
    - name: Check code formatting with Black
      run: |
        black --check .
    
    - name: Check imports with isort
      run: |
        isort --check-only --diff .
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    
    - name: Security check with Bandit
      run: |
        bandit -r . -c pyproject.toml || true
    
    - name: Check dependencies for known vulnerabilities
      run: |
        safety check 